name: Deploy changes to remote server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: |
        IP=${{secrets.VM_IP}}
        KEY='${{secrets.VM_PRIVATE_KEY}}'
        REPO='githubActionsTest'
        'command -v ssh-agent >/dev/null || ( apt-get install openssh )'
        eval $(ssh-agent -s)
        echo "$KEY" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan $IP >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=no azureuser@${IP}
        sudo apt-get update && sudo apt-get install git
        if [ ! -d $REPO ]; then
          git clone https://github.com/Apprentice76/githubActionsTest.git
        fi
        cd $REPO
        git stash
        git pull
        echo "Done updating..."
        git stash pop