name: Deploy changes to remote server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: connect via SSH
    - run: |
        IP=${{secrets.VM_IP}}
        KEY=${{secrets.VM_PRIVATE_KEY}}
        REPO='githubActionsTest'
        echo KEY > ./key.pem
        ssh -i ./key.pem -o StrictHostKeyChecking=no azureuser@${IP}
        sudo apt-get update && sudo apt-get install git
        if [ ! -d $REPO ]; then
          git clone https://github.com/Apprentice76/githubActionsTest.git
        fi
        cd $REPO
        git stash
        git pull
        echo "Done updating..."
        git stash pop